- name: Install Java 17
  apt:
    name: openjdk-17-jdk
    state: present
    update_cache: yes

- name: Install dependencies
  apt:
    name:
      - curl
      - gnupg
    state: present
    update_cache: yes

- name: Create keyring directory
  file:
    path: /usr/share/keyrings
    state: directory
    mode: '0755'

- name: Add Jenkins GPG key
  shell: |
    curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | \
    gpg --dearmor -o /usr/share/keyrings/jenkins-keyring.gpg
  args:
    creates: /usr/share/keyrings/jenkins-keyring.gpg

- name: Add Jenkins repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.gpg] https://pkg.jenkins.io/debian-stable binary/"
    state: present

- name: Install Jenkins
  apt:
    name: jenkins
    state: present
    update_cache: yes

- name: Start Jenkins
  service:
    name: jenkins
    state: started
    enabled: true