- name: Install required dependencies
  apt:
    name:
      - gnupg
      - software-properties-common
      - curl
    state: present
    update_cache: yes

- name: Add HashiCorp GPG key
  shell: |
    curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
  args:
    creates: /usr/share/keyrings/hashicorp-archive-keyring.gpg

- name: Add HashiCorp repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present
    filename: hashicorp

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Terraform
  apt:
    name: terraform
    state: present